package net.alex9849.cocktailmaker.model.eventaction;

public enum EventTrigger {
    COCKTAIL_PRODUCTION_STARTED, COCKTAIL_PRODUCTION_MANUAL_INTERACTION_REQUESTED,
    COCKTAIL_PRODUCTION_FINISHED, COCKTAIL_PRODUCTION_CANCELED,
    APPLICATION_STARTUP
}
