INSERT INTO ingredients (id, dtype, alcohol_content, name, pump_time_multiplier)
VALUES (1, 'AutomatedIngredient', 0, 'Cola', 1)
     , (2, 'AutomatedIngredient', 38, 'Triple sec', 1)
     , (3, 'AutomatedIngredient', 40, 'Tequila', 1)
     , (4, 'AutomatedIngredient', 40, 'Whiskey', 1)
     , (5, 'AutomatedIngredient', 40, 'Vodka', 1)
     , (6, 'AutomatedIngredient', 0, 'Cranberry Juice', 1)
     , (7, 'AutomatedIngredient', 38, 'Gin', 1)
     , (8, 'AutomatedIngredient', 25, 'Campari', 1)
     , (9, 'AutomatedIngredient', 20, 'Sweet Vermouth', 1)
     , (14, 'AutomatedIngredient', 12, 'Champagne', 1)
     , (10, 'AutomatedIngredient', 0, 'Ginger Beer', 1)
     , (12, 'AutomatedIngredient', 0, 'Lemon Juice', 1)
     , (11, 'AutomatedIngredient', 0, 'Lime Juice', 1)
     , (15, 'AutomatedIngredient', 0, 'Orange Juice', 1)
     , (13, 'AutomatedIngredient', 0, 'Simple Syrup', 1)
     , (16, 'AutomatedIngredient', 16, 'Dry Vermouth', 1)
     , (17, 'AutomatedIngredient', 38, 'Dark Rum', 1)
     , (18, 'AutomatedIngredient', 40, 'Cognac', 1)
     , (19, 'AutomatedIngredient', 38, 'Silver Tequila', 1)
     , (20, 'AutomatedIngredient', 0, 'Pineapple Juice', 1)
     , (21, 'AutomatedIngredient', 5, 'Mexican Beer', 1)
     , (22, 'AutomatedIngredient', 21, 'Blue Curaçao', 1)
     , (23, 'AutomatedIngredient', 40, 'Rum', 1)
     , (24, 'AutomatedIngredient', 75, 'Gold Rum', 1)
     , (25, 'AutomatedIngredient', 0, 'Red Bull', 1)
     , (26, 'AutomatedIngredient', 17, 'Chambord Liqueur', 1)
     , (27, 'AutomatedIngredient', 21, 'Malibu', 1)
     , (28, 'AutomatedIngredient', 0, 'Sprite', 1)
     , (29, 'AutomatedIngredient', 18, 'Peach Schnapps', 1)
     , (30, 'AutomatedIngredient', 40, 'Cointreau', 1)
     , (31, 'AutomatedIngredient', 40, 'Citrus Vodka', 1)
     , (32, 'AutomatedIngredient', 40, 'Grand Marnier', 1)
     , (33, 'AutomatedIngredient', 0, 'Cranberry Nectar', 1)
     , (34, 'AutomatedIngredient', 24, 'Apricot Brandy', 1)
     , (35, 'AutomatedIngredient', 0, 'Maracuja Nectar', 1)
     , (36, 'AutomatedIngredient', 0, 'Grenadine Syrup', 1)
     , (37, 'AutomatedIngredient', 20, 'Kahlúa', 1)
     , (38, 'AutomatedIngredient', 17, 'Baileys', 1)
     , (39, 'AutomatedIngredient', 40, 'Cream', 1)
     , (40, 'AutomatedIngredient', 20, 'Peach Liquor', 1)
     , (41, 'AutomatedIngredient', 0, 'Lime Syrup', 1)
     , (42, 'AutomatedIngredient', 30, 'Amaretto', 1);
SELECT setval('ingredients_id_seq', 42, true);

INSERT INTO categories (id, name)
VALUES (1, 'Classics')
    , (2, 'Vodka drinks')
    , (3, 'Fancy drinks');
SELECT setval('categories_id_seq', 3, true);

INSERT INTO users (id, email, firstname, is_account_non_locked, lastname, password, role, username)
VALUES (1, 'admin@localhost.local', 'Admin', true, 'Example',
        '$2a$10$foQL7xSRCK53J/G.MIauWOnllOS9.vyIT5RtUQT25t5ref07MtCfe', 'ROLE_ADMIN', 'admin');
SELECT setval('users_id_seq', 1, true);