INSERT INTO ingredients VALUES (1, 0, 'Cola');
INSERT INTO ingredients VALUES (2, 38, 'Triple sec');
INSERT INTO ingredients VALUES (3, 40, 'Tequila');
INSERT INTO ingredients VALUES (4, 40, 'Whiskey');
INSERT INTO ingredients VALUES (5, 40, 'Vodka');
INSERT INTO ingredients VALUES (6, 0, 'Cranberry Juice');
INSERT INTO ingredients VALUES (7, 38, 'Gin');
INSERT INTO ingredients VALUES (8, 25, 'Campari');
INSERT INTO ingredients VALUES (9, 20, 'Sweet Vermouth');
INSERT INTO ingredients VALUES (14, 12, 'Champagne');
INSERT INTO ingredients VALUES (10, 0, 'Ginger Beer');
INSERT INTO ingredients VALUES (12, 0, 'Lemon Juice');
INSERT INTO ingredients VALUES (11, 0, 'Lime Juice');
INSERT INTO ingredients VALUES (15, 0, 'Orange Juice');
INSERT INTO ingredients VALUES (13, 0, 'Simple Syrup');
INSERT INTO ingredients VALUES (16, 16, 'Dry Vermouth');
INSERT INTO ingredients VALUES (17, 38, 'Dark Rum');
INSERT INTO ingredients VALUES (18, 40, 'Cognac');
INSERT INTO ingredients VALUES (19, 38, 'Silver Tequila');
INSERT INTO ingredients VALUES (20, 0, 'Pineapple Juice');
INSERT INTO ingredients VALUES (21, 5, 'Mexican Beer');
INSERT INTO ingredients VALUES (22, 21, 'Blue Curaçao');
INSERT INTO ingredients VALUES (23, 40, 'Rum');
INSERT INTO ingredients VALUES (24, 75, 'Gold Rum');
INSERT INTO ingredients VALUES (25, 0, 'Red Bull');
INSERT INTO ingredients VALUES (26, 17, 'Chambord Liqueur');
INSERT INTO ingredients VALUES (27, 21, 'Malibu');
INSERT INTO ingredients VALUES (28, 0, 'Sprite');
INSERT INTO ingredients VALUES (29, 18, 'Peach Schnapps');